# Generated by Django 4.1.6 on 2023-11-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="clinic",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="graduation",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="specialty",
            field=models.CharField(default="N/A", max_length=50),
        ),
    ]
